import { useEffect, useState } from 'react'
import { ArrowRight, ChevronDown, Globe2, Menu, X } from 'lucide-react'
import { academicPrograms } from '../data/site'

type Lang = 'en' | 'uz' | 'ru'
type Page = 'home' | 'about' | 'academics' | 'people' | 'admissions' | 'news' | 'achievements' | 'gallery' | 'faq' | 'contact'

const t = {
  en:{home:'Home',about:'About',academics:'Academics',people:'People',admissions:'Admissions',news:'News',achievements:'Achievements',gallery:'Gallery',faq:'FAQ',contact:'Contact',title:'A place to learn. A place to become.',aboutTitle:'An academic community built for the next generation.',aboutText:'Academic Lyceum of Andijan State University gives motivated students a rigorous environment in which to learn, think independently, and prepare for university and life beyond it.',programTitle:'Strong foundations for ambitious futures.',admissionTitle:'Admissions at ALASU',admissionText:'Applications to academic lyceums are submitted through my.edu.uz. ALASU provides information and guidance through its administration.',peopleTitle:'People make the institution.',peopleText:'Our leadership, teachers, and students are the heart of ALASU.',contactTitle:'Talk to ALASU',contactText:'Have a question about admissions, programs, students, or the lyceum? Contact the administration.',explore:'Explore',info:'Admissions information',official:'Official application portal'},
  uz:{home:'Bosh sahifa',about:'Biz haqimizda',academics:'Ta’lim',people:'Jamoa',admissions:'Qabul',news:'Yangiliklar',achievements:'Yutuqlar',gallery:'Galereya',faq:'FAQ',contact:'Aloqa',title:'O‘rganish uchun. Kelajak uchun.',aboutTitle:'Kelajak avlodi uchun yaratilgan akademik hamjamiyat.',aboutText:'Andijon davlat universiteti akademik litseyi bilim olish, mustaqil fikrlash va universitetga tayyorlanish uchun kuchli akademik muhit yaratadi.',programTitle:'Katta maqsadlar uchun mustahkam poydevor.',admissionTitle:'ALASUga qabul',admissionText:'Akademik litseylarga arizalar my.edu.uz orqali topshiriladi. ALASU ma’muriyati ma’lumot va yo‘l-yo‘riq beradi.',peopleTitle:'Muassasani odamlar yaratadi.',peopleText:'Rahbariyat, o‘qituvchilar va o‘quvchilar ALASUning yuragi.',contactTitle:'ALASU bilan bog‘laning',contactText:'Qabul, dasturlar, o‘quvchilar yoki litsey haqida savolingiz bormi?',explore:'Ko‘rish',info:'Qabul haqida ma’lumot',official:'Rasmiy ariza portali'},
  ru:{home:'Главная',about:'О лицее',academics:'Обучение',people:'Команда',admissions:'Поступление',news:'Новости',achievements:'Достижения',gallery:'Галерея',faq:'FAQ',contact:'Контакты',title:'Место, где учатся. Место, где растут.',aboutTitle:'Академическое сообщество для нового поколения.',aboutText:'Академический лицей Андижанского государственного университета создаёт сильную среду для обучения, самостоятельного мышления и подготовки к университету.',programTitle:'Сильная основа для амбициозного будущего.',admissionTitle:'Поступление в ALASU',admissionText:'Заявления в академические лицеи подаются через my.edu.uz. Администрация ALASU предоставляет информацию и консультации.',peopleTitle:'Люди создают институт.',peopleText:'Руководство, преподаватели и ученики — сердце ALASU.',contactTitle:'Связаться с ALASU',contactText:'Есть вопросы о поступлении, программах или лицее?',explore:'Подробнее',info:'Информация о поступлении',official:'Официальный портал подачи'}
} as const

const routes: Record<string,Page>={'/':'home','/about':'about','/academics':'academics','/people':'people','/admissions':'admissions','/news':'news','/achievements':'achievements','/gallery':'gallery','/faq':'faq','/contact':'contact'}
function useRouter(){const [path,setPath]=useState(location.pathname);useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);return [routes[path]??'home',(p:Page)=>{history.pushState({},'',p==='home'?'/':`/${p}`);setPath(p);scrollTo({top:0,behavior:'smooth'})}] as const}

function Header({lang,setLang,page,navigate}:{lang:Lang;setLang:(l:Lang)=>void;page:Page;navigate:(p:Page)=>void}){const [open,setOpen]=useState(false);const c=t[lang];const links:Page[]=['about','academics','people','admissions','news'];return <header className={`site-header ${page==='home'?'over-hero':''}`}><div className="container site-nav"><button className="wordmark" onClick={()=>navigate('home')}><span className="crest">A</span><span><b>ALASU</b><small>Academic Lyceum</small></span></button><div className={`main-nav ${open?'is-open':''}`}><button onClick={()=>navigate('home')}>{c.home}</button>{links.map(p=><button key={p} className={page===p?'active':''} onClick={()=>{navigate(p);setOpen(false)}}>{c[p]}</button>)}</div><div className="nav-tools"><div className="lang"><Globe2 size={14}/><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">EN</option><option value="uz">UZ</option><option value="ru">RU</option></select></div><button className="header-contact" onClick={()=>navigate('contact')}>{c.contact}<ArrowRight size={14}/></button><button className="mobile-menu" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div></div></header>}

function Hero({page,lang}:{page:Page;lang:Lang}){const c=t[lang];const info:Record<Page,[string,string,string]>={about:[c.about,c.aboutTitle,c.aboutText],academics:[c.academics,c.programTitle,c.aboutText],people:[c.people,c.peopleTitle,c.peopleText],admissions:[c.admissions,c.admissionTitle,c.admissionText],news:[c.news,c.news,'Stories, announcements, and moments from ALASU.'],achievements:[c.achievements,c.achievements,'Celebrating the students and teachers who represent ALASU.'],gallery:[c.gallery,c.gallery,'A visual record of academic life and community.'],faq:[c.faq,c.faq,'Clear answers to common questions about ALASU.'],contact:[c.contact,c.contactTitle,c.contactText],home:['','','']};const d=info[page];return <section className={`page-hero ${page==='home'?'home-hero':''}`}><div className="page-hero-image"/><div className="page-hero-shade"/><div className="container page-hero-content"><p className="eyebrow light">{page==='home'?'Academic Lyceum of Andijan State University':d[0]}</p><h1>{page==='home'?c.title:d[1]}</h1><p>{page==='home'?c.aboutText:d[2]}</p></div></section>}

function Home({lang,navigate}:{lang:Lang;navigate:(p:Page)=>void}){const c=t[lang];return <><Hero page="home" lang={lang}/><section className="statement"><div className="container statement-grid"><span className="section-index">01</span><div><p className="eyebrow">{c.about}</p><h2>{c.aboutTitle}</h2><p>{c.aboutText}</p><button className="inline-link" onClick={()=>navigate('about')}>{c.explore}<ArrowRight size={15}/></button></div></div></section><section className="feature-band"><div className="container"><div className="band-heading"><div><p className="eyebrow">02 / {c.academics}</p><h2>{c.programTitle}</h2></div><p>{c.aboutText}</p></div><div className="program-grid">{academicPrograms.map(p=><button className="program-card" key={p.number} onClick={()=>navigate('academics')}><span>{p.number}</span><h3>{p.name}</h3><p>{p.description}</p><ArrowRight size={17}/></button>)}</div></div></section><section className="people-preview"><div className="people-photo"/><div className="people-panel"><p className="eyebrow light">03 / {c.people}</p><h2>{c.peopleTitle}</h2><p>{c.peopleText}</p><button className="button button-light" onClick={()=>navigate('people')}>{c.explore}<ArrowRight size={16}/></button></div></section><section className="admission-strip"><div className="container strip-grid"><div><p className="eyebrow light">04 / {c.admissions}</p><h2>{c.admissionTitle}</h2></div><div><p>{c.admissionText}</p><button className="button button-light" onClick={()=>navigate('admissions')}>{c.info}<ArrowRight size={16}/></button></div></div></section><section className="home-news"><div className="container"><div className="band-heading"><div><p className="eyebrow">05 / {c.news}</p><h2>{c.news}</h2></div><button className="inline-link" onClick={()=>navigate('news')}>{c.explore}<ArrowRight size={15}/></button></div><div className="story-grid"><article><div className="story-image story-one"/><p className="story-meta">ALASU · 2026</p><h3>Academic life, achievements, and the people behind them.</h3></article><article><div className="story-image story-two"/><p className="story-meta">ALASU · COMMUNITY</p><h3>A closer look at life inside our academic community.</h3></article></div></div></section></>}

function Interior({page,lang,navigate}:{page:Page;lang:Lang;navigate:(p:Page)=>void}){const c=t[lang];return <><Hero page={page} lang={lang}/><section className="interior-body"><div className="container interior-grid"><aside><span>ALASU</span><b>Andijan State University</b></aside><main><h2>{page==='about'?c.aboutTitle:page==='academics'?c.programTitle:page==='people'?c.peopleTitle:page==='admissions'?c.admissionTitle:page==='contact'?c.contactTitle:c[page]}</h2><p>{page==='about'?c.aboutText:page==='academics'?c.aboutText:page==='people'?c.peopleText:page==='admissions'?c.admissionText:c.contactText}</p>{page==='academics'&&<div className="detail-grid">{academicPrograms.map(p=><article key={p.number}><span>{p.number}</span><h3>{p.name}</h3><p>{p.description}</p></article>)}</div>}{page==='people'&&<div className="detail-grid"><article><span>01</span><h3>Leadership & management</h3><p>Director and management profiles will be maintained through the ALASU administration workspace.</p></article><article><span>02</span><h3>Teachers</h3><p>Faculty profiles, departments, subjects, and biographies.</p></article><article><span>03</span><h3>Students</h3><p>Student life, activities, opportunities, and community.</p></article></div>}{page==='admissions'&&<div className="action-card"><div><b>{c.official}</b><p>Applications are submitted externally through my.edu.uz.</p></div><a className="button button-dark" href="https://my.edu.uz" target="_blank" rel="noreferrer">my.edu.uz <ArrowRight size={15}/></a></div>}{page==='faq'&&<div className="faq-list">{['How does admission work?','Where are applications submitted?','How can I contact the administration?','What programs are available?'].map((q,i)=><details key={q}><summary>{q}<ChevronDown size={16}/></summary><p>{i===1?'Official applications are submitted through my.edu.uz. Other questions can be sent to ALASU administration.':'This information will be maintained through the ALASU content management system.'}</p></details>)}</div>}{page==='contact'&&<button className="button button-dark" onClick={()=>navigate('contact')}>Contact administration <ArrowRight size={15}/></button>}</main></div></section></>}

export default function SiteApp(){const [page,navigate]=useRouter();const [lang,setLang]=useState<Lang>('en');const c=t[lang];useEffect(()=>{document.title=`${c[page]} — ALASU`},[page,lang,c]);return <div className="site"><Header {...{lang,setLang,page,navigate}}/>{page==='home'?<Home {...{lang,navigate}}/>:<Interior {...{page,lang,navigate}}/>}<footer className="site-footer"><div className="container footer-grid"><div><button className="wordmark footer-mark" onClick={()=>navigate('home')}><span className="crest">A</span><span><b>ALASU</b><small>Academic Lyceum of Andijan State University</small></span></button><p>Learning with purpose. Growing with ambition.</p></div><div><b>Explore</b><button onClick={()=>navigate('about')}>{c.about}</button><button onClick={()=>navigate('academics')}>{c.academics}</button><button onClick={()=>navigate('people')}>{c.people}</button><button onClick={()=>navigate('news')}>{c.news}</button></div><div><b>Admissions</b><button onClick={()=>navigate('admissions')}>{c.admissions}</button><button onClick={()=>navigate('contact')}>{c.contact}</button><a href="https://my.edu.uz" target="_blank" rel="noreferrer">my.edu.uz ↗</a></div><div><b>Andijan</b><p>Academic Lyceum of<br/>Andijan State University</p></div></div><div className="container footer-bottom"><span>© 2026 ALASU</span><span>Andijan, Uzbekistan</span></div></footer></div>}
